### ISSUE TITLE
Allow extending of AbstractLink

### ISSUE THREAD

**Issue by silverstripesk** [Zauberfisch/silverstripe-easy-linkfield#4]
Hi Zauberfisch,

currently it is not possible to extend AbstractLink with custom field - getCMSFields() method can't be updated, so it is not possible add new field.

I need to add Button style to every link type...

**Comment by Zauberfisch** [comment]
just to make sure I understand correctly, you want to create a `AbstractLinkExtension` with `updateCMSFields()` to change the CMS fields?

Hmm, supporting `updateCMSFields` would probably be a good idea. I haven't looked into it, but it's probably a bit more complicated because of how the fields are duplicated in the list. Might take some time until I fix this.

--- 

For now, as a work around you'll have to create a new class for each link type that you want to modify. It's not clean, but it works.


```
# /app/_config/extensions.yml
# this will replace the default link types "internal" and "external" with new classes
# or use "internalButton: 'app\InternalLink'" instead if you want to create a new type to use both the default internal link and the new one
zauberfisch\LinkField\LinkListField:
  link_types:
    internal: 'app\InternalLink'
    external: 'app\ExternalLink'
```
```
<?php

declare(strict_types=1);

namespace app;

class InternalLink extends \zauberfisch\LinkField\Link\InternalLink {
  	public function getCMSFields(): FieldList {
		$fields = parent::getCMSFields();
		$fields->insertBefore(
			'NewTab',
			(new DropdownField('ButtonStyle', $this->fieldLabel('ButtonStyle'), [
			  "red" => "Red Button",
			  "green" => "Green Button",
			]))->setEmptyString("Default Button")
		);
		return $fields;
	}
}
```
```
<?php

declare(strict_types=1);

namespace app;

class ExternalLink extends \zauberfisch\LinkField\Link\ExternalLink {
  	public function getCMSFields(): FieldList {
		$fields = parent::getCMSFields();
		$fields->insertBefore(
			'NewTab',
			(new DropdownField('ButtonStyle', $this->fieldLabel('ButtonStyle'), [
			  "red" => "Red Button",
			  "green" => "Green Button",
			]))->setEmptyString("Default Button")
		);
		return $fields;
	}
}
```
